#if !canImport(ObjectiveC)
    import XCTest

    extension ScryptTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ScryptTests = [
            ("testApi", testApi),
            ("testPerformance", testPerformance),
            ("testScrypt", testScrypt),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(ScryptTests.__allTests__ScryptTests),
        ]
    }
#endif
